### ISSUE TITLE
Faulty highlighting of XPath functions

### ISSUE THREAD

**Issue by cmich** [neumannm/language-oxpath#10]
The highlighting for XPath functions seems to omit the first and the last character now.

See `normalize-space()` in the image below:

![cson-error](https://user-images.githubusercontent.com/9394306/27915430-9874000a-6266-11e7-92b8-ce5f2b78870c.png)

**Comment by neumannm** [comment]
Thank you for submitting this issue. 
In fact it does not seem to be a bug of the grammar itself, but some issue with atom. Something has changed between v1.17 and 1.18 and I have yet to find out what. I have opened an [issue](https://github.com/atom/atom/issues/14982) in their issue tracker.
Maybe the change in atom just revealed some flaw in the grammar of this package, this still has to be investigated.
